geniusdennis/urls.py
from django.urls import path

from . import views

app_name = 'geniusdennis'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:spanish_id>/vote/', views.vote, name='vote'),
    path('quiz/', views.QuizView.as_view(), name='quiz'),
    path('checkans/<int:spanish_id>/', views.QuizView.as_view(),name='quiz'),
]

studylang/urls.py
from django.contrib import admin
from django.urls import include, path
from geniusdennis.views import addword, deleteword, checkans

urlpatterns = [
    path('admin/', admin.site.urls),
    path('geniusdennis/', include('geniusdennis.urls')),
    path('addword/', addword),
    path('deleteword/<int:spanish_id>/', deleteword),
    path('checkans/<int:spanish_id>/', checkans),
]

geniusdennis/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Spanish(models.Model):
    word_esp = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date added')
    # timeswrong = models.IntegerField(default=0)

    def __str__(self):
        return self.word_esp
    def freshvocab(self):
    	now = timezone.now()
    	return now - datetime.timedelta(days=1) <= self.pub_date <= now
    freshvocab.admin_order_field = 'pub_date'
    freshvocab.boolean = True
    freshvocab.short_description = 'Added recently?'


class English(models.Model):
	spanish = models.ForeignKey(Spanish, on_delete=models.CASCADE)
	word_eng = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.word_eng

geniusdennis/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views import generic
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import user_passes_test
from django.db.models.aggregates import Count

import random
from random import sample, randint
from .models import Spanish, English

class LoginView(generic.DetailView):
	template_name = 'geniusdennis/login.html'

def email_check(user):
    return user.email.endswith('@example.com')

@user_passes_test(email_check)
def my_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    
    if user is not None:
        login(request, user)
        return HttpResponseRedirect('/geniusdennis/')
    else:
    	return HttpResponseRedirect('')

class IndexView(generic.ListView):
    template_name = 'geniusdennis/index.html'
    context_object_name = 'latest_spanish_list'

    def get_queryset(self):
	    """
	    Return the last 20 spanish words (not including those set to be
	    published in the future).
	    """
	    latest_spanish_list = Spanish.objects.filter(
	        pub_date__lte=timezone.now()
	    ).order_by('-pub_date')[:20]
	    return latest_spanish_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
	    # grab the max id in the database
        #count = self.aggregate(count=Count('id'))['count']
        #random_index = randint(0, count - 1)
        #random_spanish = Spanish.objects.get(pk__gte= random_index)[:20]
        #return self.all()[random_index]
	    
        max_id = Spanish.objects.order_by('-id')[0].id
        random_id = random.randint(1, max_id + 1)
        random_spanish = Spanish.objects.filter(id__gte=random_id)[:20]
        context['random_spanish_list'] = random_spanish
        return context

class DetailView(generic.DetailView):
    model = Spanish
    template_name = 'geniusdennis/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Spanish.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Spanish
    template_name = 'geniusdennis/results.html'

class QuizView(generic.ListView):
	template_name = 'geniusdennis/quiz.html'
	queryset = Spanish.objects.all()

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    # grab the max id in the database	    
	    max_id = Spanish.objects.order_by('-id')[0].id
	    random_id = random.randint(1, max_id + 1)
	    random_spanish_question = Spanish.objects.filter(id__gte=random_id)[0]
	    context['random_spanish_question'] = random_spanish_question
	    return context

def vote(request, spanish_id):
    spanish = get_object_or_404(Spanish, pk=spanish_id)
    try:
        selected_english = spanish.english_set.get(pk=request.POST['english'])
    except (KeyError, English.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'geniusdennis/detail.html', {
            'spanish': spanish,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_english.votes += 1
        selected_english.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('geniusdennis:results', args=(spanish.id,)))

def addword(request):
	newword_esp = Spanish(word_esp = request.POST['word_esp'], pub_date=timezone.now())
	newword_esp.save()
	newword_eng = English(word_eng = request.POST['word_eng'], spanish=newword_esp)
	newword_eng.save()
	return HttpResponseRedirect('/geniusdennis/')

def deleteword(request, spanish_id):
	word_to_delete = Spanish.objects.get(pk=spanish_id)
	word_to_delete.delete()
	return HttpResponseRedirect('/geniusdennis/')

def checkans(request, spanish_id):
	random_spanish_question = get_object_or_404(Spanish, pk=spanish_id)
	query = request.GET.get('ans')
	coreng = random_spanish_question.english_set.get()
	if query == str(coreng):
		#messages.success(request, "Correct!", extra_tags="correct")
		return render(request, ('geniusdennis/quiz.html'),{
				'message': "Correct!",
			})
		#return HttpResponseRedirect('geniusdennis/quiz.html')
	else:
		#messages.error(request, "Incorrect! The answer is " + str(coreng), extra_tags="incorrect")
		return render(request, 'geniusdennis/quiz.html', {
				'message': "Incorrect.",
				'correct_answer': "The correct answer is " + str(coreng),
			})

geniusdennis/templates/geniusdennis/detail.html
<h1>{{ spanish.word_esp }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'geniusdennis:vote' spanish.id %}" method="post">
{% csrf_token %}
{% for english in spanish.english_set.all %}
	<input type="radio" name="english" id="english{{ forloop.counter }}" value="{{ english.id }}">
    <label for="english{{ forloop.counter }}">{{ english.word_eng }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

geniusdennis/templates/geniusdennis/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'geniusdennis/style.css' %}">

<div style="width: 7vw; border: white solid 0.1em; text-align: center;">
	<a style="color: white; text-decoration: none; font-family: Gill Sans, sans-serif;" href="{% url 'geniusdennis:quiz' %}">Practise!</a>
</div>
{% if latest_spanish_list %}
<div class="flexcontainer">
	<div class="sectiontitle">Latest vocabulary
	</div>
    {% for spanish in latest_spanish_list %}
    <div class="card">
	    <div class="cardinner" onclick="this.classList.toggle('flipped');">
	    	<div class="cardfront">
	        	<a href="{% url 'geniusdennis:detail' spanish.id %}">{{ spanish.word_esp }}</a>
		        	<form action="/deleteword/{{spanish.id}}/" method="post">{% csrf_token %}
					<input type="submit" value="Delete" id="delete" />
					</form>
			</div>
			{% for english in spanish.english_set.all %}
			<div class="cardback">
				<p>{{ english.word_eng}}</p>
			</div>
			{% endfor %}
		</div>
	</div>
    {% endfor %}
</div>
{% else %}
    <p style="color: white;">No Spanish words are available.</p>
{% endif %}

{% if random_spanish_list %}
<div class="flexcontainer">
	<div class="sectiontitle">Random vocabulary
	</div>
    {% for spanish in random_spanish_list %}
    <div class="card">
	    <div class="cardinner" onclick="this.classList.toggle('flipped');">
	    	<div class="cardfront">
	        	<a href="{% url 'geniusdennis:detail' spanish.id %}">{{ spanish.word_esp }}</a>
	        	<form action="/deleteword/{{spanish.id}}/" method="post">{% csrf_token %}
				<input type="submit" value="Delete" id="delete" />
				</form>
			</div>
			{% for english in spanish.english_set.all %}
			<div class="cardback">
				<p>{{ english.word_eng}}</p>
			</div>
			{% endfor %}
		</div>
	</div>
    {% endfor %}
</div>
{% else %}
    <p style="color: white;">No Spanish words are available.</p>
{% endif %}
<div style="width: 100vw; display: flex; justify-content: center;">
	<div class="newword_input">
		<form action="/addword/" method="post">{% csrf_token %}
			<label for="esp">Spanish word:</label><input type="text" name="word_esp" required/>
			<label for="eng">English word:</label><input type="text" name="word_eng" required/>
			<input type="submit" value="Add"/>
		</form> 
	</div>
</div>

geniusdennis/templates/geniusdennis/login.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'geniusdennis/style.css' %}">

<div class="newword_input">
	<form action="/login/" method="post">{% csrf_token %}
		<label for="esp">Spanish word:</label><input type="text" name="username"/>
		<label for="eng">English word:</label><input type="text" name="password"/>
		<input type="submit" value="Add"/>
	</form> 
</div>

geniusdennis/templates/geniusdennis/quiz.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'geniusdennis/style.css' %}">
<scrip src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$("form").on('submit', function(e) { // or you can get the form by id if you set it

e.preventDefault(); // avoid to execute the actual submit of the form.

var form = $(this);
var url = form.attr('action');

$.ajax({
       type: 'GET',
       url: url,
       data: form.serialize(), // serializes the forms elements.
       success: function(data)
       {
           ... // whatever you want to do
           var alertMessage = data.message;
           if (data.correct_answer) {
               alertMessage += ' ' + data.correct_answer;
           }
           alert(alertMessage); // show response
       }
     });
});
</script>

<div style="width: 7vw; border: white solid 0.1em; text-align: center;">
	<a style="color: white; text-decoration: none; font-family: Gill Sans, sans-serif;" href="{% url 'geniusdennis:index' %}">Home page</a>
</div>
{% if random_spanish_question %}
<div class="flexcontainer" style="justify-content: center;">
	<div class="sectiontitle">Quiz time
	</div>
    	<div class="question_card">
        	<div class="question_word">{{ random_spanish_question }}</div>
        	{% if messages %}
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
			</ul>
			{% endif %}
        	<form action="/checkans/{{random_spanish_question.id}}/" method="get">{% csrf_token %}
        		<label for="ans">Answer:</label>
        		<input type="text" name="ans"autofocus autocomplete="off"/>
        		<input type="submit" value="Submit"/>
        	</form>
        <input type="submit" value="Skip"/>
        
		</div>
</div>
{% else %}
	{% if message %}
        <div class="message">
            {{ message }}
        </div>
        <div class="ans">
            {{ correct_answer }}
        </div>
    {% endif %}
{% endif %}

geniusdennis/templates/geniusdennis/results.html
<h1>{{ spanish.word_esp }}</h1>

<ul>
{% for english in spanish.english_set.all %}
    <li>{{ english.word_eng }} -- {{ english.votes }} vote{{ english.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'geniusdennis:detail' spanish.id %}">Vote again?</a>